name: Master pipeline

on:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo, mongodb, bcmath, exif, gd

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze

      - name: Run Pint
        run: vendor/bin/pint --test --config https://raw.githubusercontent.com/DIJ-digital/pint-config/f9a52276294d2b1c323f5883fdc29884d4943e54/pint.json

      - name: Cleanup
        run: composer clear-cache
