name: Master pipeline

on:
  push:
    branches:
      - master

jobs:
  analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, pdo, mongodb, bcmath, exif, gd

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze

      - name: Run Pint
        run: vendor/bin/pint --test --config https://raw.githubusercontent.com/DIJ-digital/pint-config/f9a52276294d2b1c323f5883fdc29884d4943e54/pint.json

      - name: Cleanup
        run: composer clear-cache

  deploy:
    runs-on: ubuntu-latest
    needs: analysis
    environment:
      name: production
      url: secrets.URL
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} 'cd /var/www/dashboard && git reset --hard && git pull && chmod +x deploy.sh && ./deploy.sh'
